# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2023 Graz University of Technology.
# Copyright (C) 2024 Shared RDM.
#
# invenio-override is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

name: CI

on:
  pull_request:
    branches: main
  push:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  python_tests:
    uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
    with:
      python-version: '["3.12"]'

  djlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install djlint
        run: pip install djlint
      - name: Check HTML templates
        run: djlint --check invenio_override/templates/
